env: flex
runtime: go
handlers:

# All URLs are handled by the Go application script
# -url: /.*
#   script: _go_app
- url: /
  static_files: index.html
  upload: index.html
- url: /static
  static_dir: static
- url: /styles
  static_dir: styles